version: "3.3"
networks:
  main:
services:
  product-service_1:
    image: product-service:latest
    networks:
      - main
  product-service_2:
    image: product-service:latest
    networks:
      - main
  proxy:
    image: proxy:latest
    ports: 
      - "5300:5300"
    networks:
      - main
  mongo:
    image: mongo
    networks:
     - main
